"""Token-by-token streaming handler for the Streamlit UI.

Extends LangChain's callback system to provide a typewriter effect:
tokens appear one by one as the LLM generates them, with a blinking
cursor (▌) to indicate ongoing generation.

Rendering is throttled to avoid overwhelming the browser — the UI
is updated at most every 30 ms.
"""

from __future__ import annotations

import time
from typing import Any

from langchain_core.callbacks import BaseCallbackHandler

from documate_ai.config import STREAM_RENDER_INTERVAL_SECONDS


class StreamHandler(BaseCallbackHandler):
    """Streams LLM tokens into a Streamlit container with throttling.

    Attributes:
        container: The Streamlit container (e.g. ``st.empty()``) where
            the streaming text is rendered.
        text: The accumulated response text so far.
    """

    def __init__(self, container: Any) -> None:
        """Initialise the stream handler.

        Args:
            container: A Streamlit container object that supports
                ``.markdown()`` for rendering.
        """
        self.container = container
        self.text: str = ""
        self._last_render_time: float = 0.0

    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """Called by LangChain for every new token generated by the LLM.

        Accumulates the token and re-renders the container if enough
        time has elapsed since the last render (throttling).

        Args:
            token: The newly generated token string.
            **kwargs: Additional callback metadata (unused).
        """
        self.text += token
        now = time.monotonic()
        if (now - self._last_render_time) >= STREAM_RENDER_INTERVAL_SECONDS:
            self.container.markdown(self.text + "▌")
            self._last_render_time = now

    def finalize(self) -> str:
        """Render the final text without the cursor and return it.

        Returns:
            The complete accumulated response text.
        """
        self.container.markdown(self.text)
        return self.text
