[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "DocuMate-AI"
version = "0.1.0"
description = "DocuMate-AI is an intelligent, on-device PDF analysis chatbot built with LangChain and Ollama, providing private, scalable document intelligence through semantic caching and pinpoint citations."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

dependencies = [
    "langchain==1.2.10",
    "langchain-core==1.2.17",
    "langchain-community==0.4.1",
    "langchain-ollama==1.0.1",
    "langchain-chroma==1.1.0",
    "langchain-text-splitters==1.1.1",
    "pypdf",
    "streamlit",
    "chromadb",
    "ollama",
    "numpy",
]

[tool.hatch.build.targets.wheel]
packages = ["src/documate_ai"]
